spring.application.name=SpringFirstWeb
server.port=8083
# Data source configuration
spring.datasource.url=jdbc:postgresql://localhost:5342/databasename
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.driver-class-name=com.postgresql.cj.jdbc.Driver

# Enable Hibernate SQL logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.date-format=dd/MM/yyyy




spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=042784f134c46b
spring.mail.password=4a51b8e9bf4b9d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true

#JavaMailSender

